### ISSUE TITLE
afterSave method override issue

### ISSUE THREAD

**Issue by vkmel** [asinfotrack/yii2-audittrail#14]
When afterSave method is overridden in the Model, AuditTrail does not log. How can I manually initiate the logging process at the end of my AfterSave method? Thank you.

**Comment by pasci84** [comment]
Hey there!

There is no need to manually trigger it. Simply assert, that the events are thrown!

The behavior listens to the Events of `ActiveRecord` (in your case `ActiveRecord::EVENT_AFTER_INSERT` and `ActiveRecord::EVENT_AFTER_UPDATE`). Whenever one of those is triggered, it does its job (see [here](https://github.com/asinfotrack/yii2-audittrail/blob/379c91767b8fa421d6ff2d40c3115b86a916ce8a/behaviors/AuditTrailBehavior.php#L116)). It will also listen to `ActiveRecord::EVENT_BEFORE_DELETE` to log deletions.

If you now override the `afterSave`-method of the model, you either need to call the parent implementation (`parent::afterSave($insert, $changedAttributes)`) or trigger the corresponding event yourself. You can see [here](https://github.com/yiisoft/yii2/blob/1a8c83ba438f92075fc6e4ab9124b6ae59fdda8f/framework/db/BaseActiveRecord.php#L997) how this is done in the original `BaseActiveRecord` class. You can simply copy those three lines if you prefer not to call the parent implementation.

If this does not help, then please post a snipped so we can look into it in detail.

Have a good one!

**Comment by vkmel** [comment]
Perfect! `parent::afterSave($insert, $changedAttributes);` at the end of overridden afterSave method did the trick. Thanks again.
