### ISSUE TITLE
Save only allowed attributes

### ISSUE THREAD

**Issue by sokollondon** [asinfotrack/yii2-audittrail#16]
Is there such a functional?
For example, can only one attribute `price` be saved?

**Comment by Isitar** [comment]
in the current logic you have to exclude every column you don't want with `ignoredAttributes`

You can either overwrite the `getRelevantDbAttributes` function or ignore every other attribute with `array_filter(array_keys($this->getTableSchema()->columns), function($col) { return 'price' !== $col; })`
