### ISSUE TITLE
No record should be created if only changed attribute is in ignored attribute array

### ISSUE THREAD

**Issue by akorinek** [asinfotrack/yii2-audittrail#2]
I've got a table where the field last_seen gets updated every 30 seconds. The last_seen field is in the ignoredAttributes array. The audittrail behavior now creates empty rows. It should not create any row in this case, since no change is being recorded.

**Comment by pasci84** [comment]
Hey @akorinek
Thanks for submitting the issue. You are right of course...
I'll have a look at this and fix it in the next two days!

**Comment by pasci84** [comment]
Took a little more time, sorry! Your issue should now be fixed. Also the comparison of actual changes has been extended and made type-safe for numerical and boolean types. Check out the [changelog](https://github.com/asinfotrack/yii2-audittrail/blob/master/README.md#changelog) for details.
