### ISSUE TITLE
Callbacks for changed fields values

### ISSUE THREAD

**Issue by smartfin** [asinfotrack/yii2-audittrail#3]
Thank you for great extension.

Also it is great feature with 'userIdCallback' in widget.
i'm only wonder about such possibility for callback to display changed attributes( i mean inside column Data value of  cells  'From' and 'To'.

For now i can not find this functionality. Maybe i just looking in wrong place?

**Comment by smartfin** [comment]
I sent pull request, maybe that would be helpful

**Comment by pasci84** [comment]
Hey @smartfin 

Thanks for you feedback. No, you're right...the widget is still pretty basic. I just overlooked your code, which looks fine. I'll extend your comments a little (type descriptions, etc.) and will integrate your pull-request by wednesday. Thanks for your time and help!

**Comment by pasci84** [comment]
Hello again!

When double-checking your code I saw that the feature you request is actually already there. It isn't in the widget but within the behavior configuration. That way you don't have to redeclare it everytime you create a widget-instance. Simply put your callback withink the `attributeOutput`-property of the behavior as described [here](https://github.com/asinfotrack/yii2-audittrail#behavior). Yout can either use a standard format as a string (eg `date`, `currency`, etc.) or provide a custom callback as in your code.

Does this solve your problem or are you looking for the possibility to override it from a widget-instance?

**Comment by smartfin** [comment]
Thank you for your response. Yes, that configuration of behavior is useful and solve my issue. I just didn't find it.
Not sure that anyone need possibility to override output in single widget instance :) But you can decide if it is useful enhancement or not

**Comment by pasci84** [comment]
I will implement it in one of the next releases anyway...could help someone somewhen :+1:
