### ISSUE TITLE
Undefined property: yii\web\User::$isGuest

### ISSUE THREAD

**Issue by smartfin** [asinfotrack/yii2-audittrail#5]
I discover such type of error. It happens in case of user inactivity, and then user trying to make some action in the same tab. As i can understand it is issue with renewAuthStatus and loginByCookie + magic getter for $isGuest. It looks like at moment behaviour is called, User object is not constructed.

As i found [here](https://github.com/yiisoft/yii2/issues/9563)  and [here](http://www.yiiframework.com/forum/index.php/topic/55466-user-identity-default-scope-problem/)  and [here](http://www.yiiframework.com/forum/index.php/topic/61451-problem-with-isguest/) is to use function `getIsGuest()` instead of property `isGuest`. 

I also created pull request for that small issue

```
exception 'yii\base\ErrorException' with message 'Undefined property: yii\web\User::$isGuest' in /var/www/vendor/asinfotrack/yii2-audittrail/behaviors/AuditTrailBehavior.php:232
Stack trace:
#0 /var/www/vendor/asinfotrack/yii2-audittrail/behaviors/AuditTrailBehavior.php(163): asinfotrack\yii2\audittrail\behaviors\AuditTrailBehavior->createPreparedAuditTrailEntry()
#1 /var/www/vendor/yiisoft/yii2/base/Component.php(541): asinfotrack\yii2\audittrail\behaviors\AuditTrailBehavior->onAfterUpdate()
#2 /var/www/vendor/yiisoft/yii2/base/Component.php(541): ::call_user_func()
#3 /var/www/vendor/yiisoft/yii2/db/BaseActiveRecord.php(911): yii\base\Component->trigger()
#4 /var/www/common/models/User.php(155): yii\db\BaseActiveRecord->afterSave()
#5 /var/www/vendor/yiisoft/yii2/db/BaseActiveRecord.php(739): common\models\User->afterSave()
#6 /var/www/vendor/yiisoft/yii2/db/ActiveRecord.php(533): yii\db\BaseActiveRecord->updateInternal()
#7 /var/www/vendor/yiisoft/yii2/db/BaseActiveRecord.php(595): yii\db\ActiveRecord->update()
#8 /var/www/common/behaviors/LoginTimestampBehavior.php(36): yii\db\BaseActiveRecord->save()
#9 /var/www/vendor/yiisoft/yii2/base/Component.php(541): common\behaviors\LoginTimestampBehavior->afterLogin()
#10 /var/www/vendor/yiisoft/yii2/base/Component.php(541): ::call_user_func()
#11 /var/www/vendor/yiisoft/yii2/web/User.php(473): yii\base\Component->trigger()
#12 /var/www/vendor/yiisoft/yii2/web/User.php(307): yii\web\User->afterLogin()
#13 /var/www/vendor/yiisoft/yii2/web/User.php(631): yii\web\User->loginByCookie()
#14 /var/www/vendor/yiisoft/yii2/web/User.php(176): yii\web\User->renewAuthStatus()
#15 /var/www/vendor/yiisoft/yii2/web/User.php(346): yii\web\User->getIdentity()
#16 /var/www/vendor/yiisoft/yii2/base/Component.php(130): yii\web\User->getIsGuest()
#17 /var/www/vendor/yiisoft/yii2/base/Component.php(46): yii\base\Component->__get()
#18 /var/www/vendor/yiisoft/yii2/base/Component.php(541): common\behaviors\LocaleBehavior->beforeRequest()
#19 /var/www/vendor/yiisoft/yii2/base/Component.php(541): ::call_user_func()
#20 /var/www/vendor/yiisoft/yii2/base/Application.php(372): yii\base\Component->trigger()
#21 /var/www/backend/web/index.php(23): yii\base\Application->run()
#22 {main}
```

**Comment by pasci84** [comment]
Thanks for pointing that one out. Seems like a bug in the framework!? Usually this gets called automatically as `isGuest` will trigger a call to `getIsGuest()`. But after reading the discussions I'd say its better to choose the safer way as you suggested...!

**Comment by pasci84** [comment]
You pull-request was merged into the master branch. Thanks again!

**Comment by cebe** [comment]
> Seems like a bug in the framework!?

FYI: this happens because PHP does not support magic properties inside of __get() call and below.
In the above stack trace `#17` a call to `__get()` on user object is made, which triggers a lot of things. Down the chain another recursive call to `isGuest` is made which would need again call `__get()` but PHP does not support this to avoid looping.

**Comment by pasci84** [comment]
Thanks a lot @cebe for this insight...I didn't dive in that deep. This makes sense now of course!

**Comment by marcovtwout** [comment]
@cebe Small addition to your explanation: PHP prevents recursive calls to __get() **for the same property**. So theoretically you can still call other magic properties on WebUser. Also see https://bugs.php.net/bug.php?id=71254
