### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by akorinek** [asinfotrack/yii2-audittrail#8]
Hi,

I'm getting an error in AuditTrailEntry.php line 95 when using PHP 7.2:

count(): Parameter must be an array or an object that implements Countable

**Comment by tomlutzenberger** [comment]
Hi @akorinek, thanks for reporting.

**PHP 7.2 Upgrade notes:**
https://github.com/php/php-src/blob/php-7.2.0RC4/UPGRADING#L226
> count() now raises a warning when an invalid parameter is passed.
> Only arrays and objects implementing the Countable interface should be passed.

We need to check against `null` at some places:
https://github.com/asinfotrack/yii2-audittrail/search?utf8=%E2%9C%93&q=count

**Comment by pasci84** [comment]
Hey @akorinek 
Thanks for your issue and your pull requests! We merged them already and will integrate them into our next release after testing. We will keep you posted and close the issue when the release is out. Thanks again for your time!
